; ====================================================================
;  Carry Robot – STM32 Slave (BlackPill F411)
;  100% Native STM32Cube HAL + Embedded C++ OOP (C++17)
; ====================================================================
[platformio]
default_envs = blackpill_f411ce

[env:blackpill_f411ce]
platform          = ststm32
board             = blackpill_f411ce
framework         = stm32cube
monitor_speed     = 115200
platform_packages =
    toolchain-gccarmnoneeabi@~1.120301.0
build_flags       =
    -std=gnu++17
    -O2
    -I include
